apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

nameSuffix: -development
patches:
  - path: Service-patch.yaml
    target:
      kind: Service
      name: simple-node-react