apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

nameSuffix: -development
namespace: development
patches:
  - path: service-path.yaml
    target:
      kind: Service
      name: simple-node-react
images:
  - name: thanh8804/react-app
    newTag: "76"
