apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-node-react
  template:
    metadata:
      labels:
        app: simple-node-react
    spec:
      containers:
      - name: simple-node-react
        image: thanh8804/react-app:69
        ports:
        - containerPort: 3000