# base/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: simple-node-react
spec:
  type: NodePort
  selector:
    app: simple-node-react
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30001
