resources:
  - ../../base

nameSuffix: -production

namespace: production
patches:
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: simple-node-react
images:
  - name: thanh8804/react-app
    newTag: ${BUILD_NUMBER}
# This file is intentionally left blank.