resources:
  - ../../base

nameSuffix: -production

namespace: production
patches:
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: simple-node-react
# This file is intentionally left blank.