apiVersion: apps/v1
kind: Deployment
metadata:
  name: reac-app-deployment
  namespace: application-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: thanh8804/react-app:latest
        ports:
        - containerPort: 3000