apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: application-deployment
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30001