# overlays/production/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: simple-node-react-prod
resources:
  - ../../base
  - namespace.yaml
patchesStrategicMerge:
  - config-patch.yaml
  - deployment-patch.yaml
commonLabels:
  environment: production
